server:
  port: 9110

spring:
  application:
    name: stock
  flyway:
    schemas: stock

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null

stock:
  order-expiration-in-minutes: 2

logging:
  level:
    org.springdoc: DEBUG

scheduler:
  order-expiration-cron: "0 * * * * ?"
